// apps/vue3-micro-app/src/pages/Home.vue
<template>
  <div>
    <a-card style="margin-bottom: 24px">
      <div style="text-align: center">
        <a-typography-title :level="2">
          欢迎使用 Vue3 微应用
        </a-typography-title>
        <a-typography-paragraph>
          这是一个基于 Vue3 + TypeScript + Ant Design Vue + Pinia 构建的微前端应用示例。
          它展示了如何在 qiankun 框架中集成 Vue3 应用。
        </a-typography-paragraph>
      </div>
      
      <a-row :gutter="[16, 16]">
        <a-col :span="6" v-for="(feature, index) in features" :key="index">
          <a-card
            hoverable
            style="text-align: center; height: 200px"
            :body-style="{ 
              display: 'flex', 
              flexDirection: 'column', 
              justifyContent: 'center',
              height: '100%'
            }"
            @click="navigateTo(feature.path)"
          >
            <a-space direction="vertical" size="middle">
              <component :is="feature.icon" style="font-size: 24px" :style="{ color: feature.color }" />
              <a-typography-title :level="4" style="margin: 0">
                {{ feature.title }}
              </a-typography-title>
              <a-typography-paragraph style="margin: 0; color: #666">
                {{ feature.description }}
              </a-typography-paragraph>
            </a-space>
          </a-card>
        </a-col>
      </a-row>
    </a-card>

    <a-row :gutter="16">
      <a-col :span="12">
        <a-card title="技术栈">
          <a-space direction="vertical" style="width: 100%">
            <div>✅ Vue 3</div>
            <div>✅ TypeScript</div>
            <div>✅ Ant Design Vue</div>
            <div>✅ Vue Router</div>
            <div>✅ Pinia</div>
            <div>✅ Vite</div>
          </a-space>
        </a-card>
      </a-col>
      
      <a-col :span="12">
        <a-card title="特性">
          <a-space direction="vertical" style="width: 100%">
            <div>🚀 快速开发</div>
            <div>📦 组合式API</div>
            <div>🎨 响应式设计</div>
            <div>🔒 类型安全</div>
            <div>⚡ 极速构建</div>
            <div>🔥 热更新</div>
          </a-space>
        </a-card>
      </a-col>
    </a-row>
  </div>
</template>

<script setup lang="ts">
import { useRouter } from 'vue-router';
import {
  ShoppingOutlined,
  OrderedListOutlined,
  BarChartOutlined,
  SettingOutlined,
} from '@ant-design/icons-vue';

const router = useRouter();

const features = [
  {
    title: '产品管理',
    description: '管理产品信息和库存',
    icon: ShoppingOutlined,
    color: '#1890ff',
    path: '/products',
  },
  {
    title: '订单管理',
    description: '处理订单和发货',
    icon: OrderedListOutlined,
    color: '#52c41a',
    path: '/orders',
  },
  {
    title: '数据分析',
    description: '分析销售数据',
    icon: BarChartOutlined,
    color: '#faad14',
    path: '/analytics',
  },
  {
    title: '系统设置',
    description: '配置应用参数',
    icon: SettingOutlined,
    color: '#f5222d',
    path: '/settings',
  },
];

const navigateTo = (path: string) => {
  router.push(path);
};
</script>

// apps/react-micro-app/src/pages/Home.tsx
import React from 'react';
import { Card, Typography, Space, Button, Row, Col } from 'antd';
import { useNavigate } from 'react-router-dom';
import {
  DashboardOutlined,
  UserOutlined,
  BarChartOutlined,
  SettingOutlined,
} from '@ant-design/icons';

const { Title, Paragraph } = Typography;

const Home: React.FC = () => {
  const navigate = useNavigate();

  const features = [
    {
      title: '数据仪表板',
      description: '查看实时数据和统计信息',
      icon: <DashboardOutlined style={{ fontSize: '24px', color: '#1890ff' }} />,
      path: '/dashboard',
    },
    {
      title: '用户管理',
      description: '管理系统用户和权限',
      icon: <UserOutlined style={{ fontSize: '24px', color: '#52c41a' }} />,
      path: '/users',
    },
    {
      title: '数据分析',
      description: '深入分析业务数据',
      icon: <BarChartOutlined style={{ fontSize: '24px', color: '#faad14' }} />,
      path: '/analytics',
    },
    {
      title: '系统设置',
      description: '配置应用参数',
      icon: <SettingOutlined style={{ fontSize: '24px', color: '#f5222d' }} />,
      path: '/settings',
    },
  ];

  return (
    <div>
      <Card style={{ marginBottom: 24 }}>
        <Space direction="vertical" size="large" style={{ width: '100%' }}>
          <div style={{ textAlign: 'center' }}>
            <Title level={2}>欢迎使用 React 微应用1</Title>
            <Paragraph>
              这是一个基于 React 18 + TypeScript + Ant Design 构建的微前端应用示例。
              它展示了如何在 qiankun 框架中集成 React 应用。
            </Paragraph>
          </div>
          
          <Row gutter={[16, 16]}>
            {features.map((feature, index) => (
              <Col span={6} key={index}>
                <Card
                  hoverable
                  style={{ textAlign: 'center', height: '200px' }}
                  bodyStyle={{ 
                    display: 'flex', 
                    flexDirection: 'column', 
                    justifyContent: 'center',
                    height: '100%'
                  }}
                  onClick={() => navigate(feature.path)}
                >
                  <Space direction="vertical" size="middle">
                    {feature.icon}
                    <Title level={4} style={{ margin: 0 }}>
                      {feature.title}
                    </Title>
                    <Paragraph style={{ margin: 0, color: '#666' }}>
                      {feature.description}
                    </Paragraph>
                  </Space>
                </Card>
              </Col>
            ))}
          </Row>
        </Space>
      </Card>

      <Row gutter={16}>
        <Col span={12}>
          <Card title="技术栈">
            <Space direction="vertical" style={{ width: '100%' }}>
              <div>✅ React 18</div>
              <div>✅ TypeScript</div>
              <div>✅ Ant Design</div>
              <div>✅ React Router</div>
              <div>✅ Webpack 5</div>
            </Space>
          </Card>
        </Col>
        
        <Col span={12}>
          <Card title="特性">
            <Space direction="vertical" style={{ width: '100%' }}>
              <div>🚀 热更新开发</div>
              <div>📦 模块化架构</div>
              <div>🎨 响应式设计</div>
              <div>🔒 类型安全</div>
              <div>⚡ 性能优化</div>
            </Space>
          </Card>
        </Col>
      </Row>
    </div>
  );
};

export default Home;
